const ACTIONS = [
  ["participation mensuelle", 5],
  ["Retard entraînement 1 min", 1],
  ["Retard entraînement 5 min", 2],
  ["Retard entraînement 10 min ou +", 5],
  ["Absence non justifié à l'entrainement", 10],
  ["Retard match", 5],
  ["Oubli tenu de match", 8],
  ["Absence non justifié au match", 50],
  ["Oubli de chasuble", 3],
  ["Oubli de vêtement hors chasuble", 5],
  ["Taxer une serviette de douche", 3],
  ["Taxer du savon", 1],
  ["Taxer de la crème", 0.5],
  ["Carton Rouge direct", 10],
  ["Carton rouge / Exclusion 2min répétée", 5],
  ["2min pour avoir râler", 2],
  ["Carton bleu", 15],
  ["Pas de logo BISCHO pour le déplacement", 2],
  ["Ballon dégueulasse (vraiment !)", 5],
  ["Oubli du ballon (match / entrainement)", 4],
  ["Taxer de l'eau", 2],
  ["Pas présent repas après match domicile", 5],
  ["Ne prend pas sa douche en déplacement", 10],
  ["Nom dans le journal", 2],
  ["Photo dans le journal", 4],
  ["Pire action du match (+ déguisement)", 1],
  ["Ballon dans la tête", 2],
  ["Autre (à préciser)", 1],
];